version: '3.8'

services:
  web-app:
    build:
      context: .
      target: runner
      env_file:
        - .env
    ports:
      - "3000:3000"
      - "8080:8080"
      - "5000:3000"
      - "8080:3000"
 
    volumes:
      - ./app.js/app/app.js
      - ./public:/app/public
      - /app/node_modules
    command: ["nodemon" ,"app.js"]
    restart: unless-stopped

