version: '3.8'

services:
  web-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      # Docker Compose יקח את הערכים מהקובץ .env ויזריק אותם לקונטיינר
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET=${S3_BUCKET} 
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules